version: '3'
services:
  nodejs-server:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3080:3080"
    container_name: node-back
    volumes:
       - ./back:/usr/src/app/back
       - /usr/src/app/back/node_modules
  angular-ui:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "4201:4201"
    container_name: angular-front
    volumes:
       - ./front:/usr/src/app/front
       - /usr/src/app/front/node_modules